'use client'
import { useState } from 'react'
import { AgentPage, Field, TextInput, NumberInput, SelectInput, CheckboxGroup } from '@/components/agents/AgentShell'

const MEMO_TYPES = [{ value: 'formal_appeal_letter', label: 'Formal appeal letter' }, { value: 'denial_response', label: 'Denial response email' }, { value: 'eob_explanation', label: 'EOB explanation note' }, { value: 'member_followup_email', label: 'Member follow-up email' }]
const AUDIENCES = [{ value: 'payer', label: 'Payer (BCBS / Aetna / UHC)' }, { value: 'agent_only', label: 'Agent only' }, { value: 'compliance', label: 'Compliance' }, { value: 'member', label: 'Member' }]
const COMPLIANCE = [{ value: 'HIPAA-US', label: 'HIPAA (US Federal)' }, { value: 'TX-DOI', label: 'TX Department of Insurance' }, { value: 'NY-DFS', label: 'NY DFS' }, { value: 'CMS', label: 'CMS (Federal)' }]
const SECTIONS = [{ value: 'denial_summary', label: 'Denial summary' }, { value: 'medical_necessity', label: 'Medical-necessity argument' }, { value: 'supporting_docs', label: 'Supporting documents' }, { value: 'next_steps', label: 'Next steps' }]

export default function AppealDrafterPage() {
  const [clientId, setClientId] = useState('MEM-LPZ-3318-2204')
  const [claimId, setClaimId] = useState('CLM-8902-1404')
  const [memoType, setMemoType] = useState('formal_appeal_letter')
  const [audience, setAudience] = useState('payer')
  const [maxWords, setMaxWords] = useState('600')
  const [complianceRegion, setComplianceRegion] = useState('HIPAA-US')
  const [mustInclude, setMustInclude] = useState(['denial_summary', 'medical_necessity', 'supporting_docs', 'next_steps'])
  const [transcriptUri, setTranscriptUri] = useState('s3://ah-notes/call_20260518.txt')
  const [briefUri, setBriefUri] = useState('s3://ah-notes/BRF-MTG-2026-05-19-001.json')

  const buildPayload = () => {
    if (!clientId || !claimId) return null
    return {
      agent: 'appeal_drafter', version: '1.0', agent_id: 'AH-04812',
      memo_type: memoType,
      subject: { member_id: clientId, claim_id: claimId },
      sources: [
        { type: 'call_transcript', uri: transcriptUri },
        { type: 'prior_brief', uri: briefUri },
      ].filter(s => s.uri),
      audience, format: 'markdown',
      must_include: mustInclude,
      max_words: Number(maxWords),
      compliance_region: complianceRegion,
    }
  }

  return (
    <AgentPage
      agentId="appeal_drafter" label="Appeal Drafter" icon="FileText"
      tagline="Appeal narrative, action items & HIPAA flags from a member call" color="#d97706" latency="~27s"
      buildPayload={buildPayload}
      form={
        <>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
            <Field label="Member ID"><TextInput value={clientId} onChange={setClientId} placeholder="MEM-LPZ-3318-2204" /></Field>
            <Field label="Claim ID"><TextInput value={claimId} onChange={setClaimId} placeholder="CLM-8902-1404" /></Field>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
            <Field label="Memo type"><SelectInput value={memoType} onChange={setMemoType} options={MEMO_TYPES} /></Field>
            <Field label="Audience"><SelectInput value={audience} onChange={setAudience} options={AUDIENCES} /></Field>
          </div>
          <Field label="Call transcript (S3 URI)" hint="Transcript of the member call"><TextInput value={transcriptUri} onChange={setTranscriptUri} placeholder="s3://ah-notes/..." /></Field>
          <Field label="Prior brief (S3 URI)" hint="Pre-meeting brief generated by Meeting Preparer"><TextInput value={briefUri} onChange={setBriefUri} placeholder="s3://ah-notes/..." /></Field>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
            <Field label="Max words"><NumberInput value={maxWords} onChange={setMaxWords} min={100} max={2000} /></Field>
            <Field label="Compliance region"><SelectInput value={complianceRegion} onChange={setComplianceRegion} options={COMPLIANCE} /></Field>
          </div>
          <Field label="Must-include sections"><CheckboxGroup value={mustInclude} onChange={setMustInclude} options={SECTIONS} /></Field>
        </>
      }
    />
  )
}
